module VerifyExamples.Main.SumDecoder8 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Main exposing (..)
import Json.Decode exposing (decodeString)







spec8 : Test.Test
spec8 =
    Test.test "#sumDecoder: \n\n    decodeString sumDecoder \"\"\"{\"x\":1,\"y\":2}\"\"\"\n    --> Ok 3" <|
        \() ->
            Expect.equal
                (
                decodeString sumDecoder """{"x":1,"y":2}"""
                )
                (
                Ok 3
                )